# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
  terraform {
    backend "remote" {
      organization = "homelab"
      workspaces {
        name = "instance-oracle-citadel"
      }
    }
  }
