# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "4.110.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 2.10.0"
    }
  }
}

provider "oci" {
  tenancy_ocid     = var.oci_profile.tenancy
  user_ocid        = var.oci_profile.user
  private_key_path = var.oci_profile.key_file
  fingerprint      = var.oci_profile.fingerprint
  region           = var.oci_profile.region
}

variable "oci_profile" {
  type = object({
    tenancy     = string
    user        = string
    key_file    = string
    fingerprint = string
    region      = string
    compartment = string
  })
}

provider "cloudflare" {
  email   = var.cloudflare_email
  api_key = var.cloudflare_token
}
