global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'routers'
    static_configs:
      - targets: ['192.168.15.156:9100']
        labels:
          area: 'office'
      - targets: ['192.168.15.147:9100']
        labels:
          area: 'tv'
      - targets: ['192.168.15.77:9100']
        labels:
          area: 'lounge'
    metric_relabel_configs:
      - source_labels: [ifname, __name__]
        regex: 'wlan0;wifi_.*'
        target_label: 'band'
        replacement: '5.0'
      - source_labels: [ifname, __name__]
        regex: 'wlan1;wifi_.*'
        target_label: 'band'
        replacement: '2.4'

