#cloud-config

hostname: controller
manage_etc_hosts: true

users:
  - name: bltavares
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,docker,netdev,video
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5027ecdYFEWCaO45DuB2681dIYS7ThssorL61x9FZPp7TL1Ul+g84kGlHSRjs7btPpqilhq4G8cC8qLE28uNNTdRMGvxWqWYJvpXIYUeiGlNS+Tm8XsUxJ6XAlAdXmLXH5Mu2T2Glqh7vugpOGEiDZTmxHGcsU2SlcQthRQNrDKhMl5k9IgNsJxxbGM1PzFlCumF3HTM/RK0hYKdwdnj4THqMb7iTRQdVuFobVrqz/U8Gdv6CAHdieU/3YmLr+Pphrm8rWXjQMr3Yn22jzMq0FXreM1e76emN+UHfwf3MmSVVTeaEndbBpVXV1LANNXlYAv9QNiR0kXyBhGFhRvaz bltav@Vaporware

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
 - ntp
 - libnss-mdns
 # Not needed on Hypriot v10
 - ssh-import-id
 # Controller
 - bridge-utils
 - wiringpi
 - python-rpi.gpio
 - minicom

locale: "en_US.UTF-8"
timezone: "UTC"

# These commands will be ran once on first boot only
runcmd:
  - 'systemctl enable github-keys@bltavares.timer'
  # Controller
  ## Configures network after initial setup
  - 'mv /etc/network/interfaces.controller /etc/network/interfaces'
  - 'cat /etc/dhcpcd.conf.controller >> /etc/dhcpcd.conf'
  - 'systemctl enable clusterhat.timer'
  - 'reboot'
  
write_files:
  - content: |
      [Unit]
      Description=Import keys on boot and keep updated
      [Timer]
      OnBootSec=1min
      OnUnitActiveSec=1d 
      [Install]
      WantedBy=timers.target
    path: /etc/systemd/system/github-keys@.timer

  - content: |
      [Unit]
      Description=Import keys for %i
      Wants=network-online.target
      After=network-online.target
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/ssh-import-id gh:%i
      User=%i
    path: /etc/systemd/system/github-keys@.service

  # Controller
  - content: |
      [Unit]
      Description=Turn on clusterhat
      [Timer]
      OnBootSec=1min
      [Install]
      WantedBy=timers.target
    path: /etc/systemd/system/clusterhat.timer

  - content: |
      [Unit]
      Description=Turn on clusterhat
      Wants=network-online.target
      After=network-online.target
      [Service]
      Type=oneshot
      ExecStartPre=/sbin/iptables -P FORWARD ACCEPT
      ExecStart=/sbin/clusterhat on
    path: /etc/systemd/system/clusterhat.service

  ## Content to show on login console
  - content: |
      HypriotOS (Debian GNU/Linux 9) \n \l
      br0 - IPv4: \4{br0} IPv6: \6{br0}
      eth0 - IPv4: \4{eth0} IPv6: \6{eth0}
    path: /etc/issue
    
  - content: UDEV_RULES
    encoding: b64
    path: /etc/udev/rules.d/90-clusterhat.rules

  - content: CLUSTERHAT
    encoding: b64
    path: /sbin/clusterhat
    permissions: '0755'
    owner: root:root

  - content: INTERFACES
    encoding: b64
    path: /etc/network/interfaces.d/clusterhat

  - content: |
      #!/bin/bash
      # Cluster HAT
      # copymac <sourceif> <destif>
      # Copies MAC address from sourceid to destif
      SMAC=$(/bin/cat /sys/class/net/$1/address)
      /sbin/ip link set $2 address $SMAC
    path: /sbin/copyMAC
    permissions: '0755'
    owner: root:root

  - content: |
      # interfaces(5) file used by ifup(8) and ifdown(8)
      # Include files from /etc/network/interfaces.d:
      source-directory /etc/network/interfaces.d
      auto br0
      iface br0 inet manual
        bridge_ports eth0
        bridge_stp off
        bridge_waitport 0
        bridge_fd 0
        post-up /sbin/copyMAC eth0 br0
    path: /etc/network/interfaces.controller
    
  - content: |
      ##  Fallback ip configuration
      denyinterfaces eth0 ethpi1 ethpi2 ethpi3 ethpi4
      profile clusterhat_fallback_br0
      static ip_address=172.19.181.254/24
      interface br0
      fallback clusterhat_fallback_br0
    path: /etc/dhcpcd.conf.controller

  ## Connection over serial - minicom pX
  - content: |
      pu port             /dev/ttypi1
    path: /etc/minicom/minirc.p1

  - content: |
      pu port             /dev/ttypi2
    path: /etc/minicom/minirc.p2

  - content: |
      pu port             /dev/ttypi3
    path: /etc/minicom/minirc.p3

  - content: |
      pu port             /dev/ttypi4
    path: /etc/minicom/minirc.p4